name: Render files

on: [push]

jobs:
  render_drawio:
    runs-on: ubuntu-latest
    name: Render draw.io files
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Render draw.io files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1.0.3
      id: render
      with: # Showcasing the default values here
        formats: 'svg'
        sub-dirs: 'docs'
        skip-dirs: '.git'
        # files: '' # unset, specify `dest-file=src-file` mappings here
        log-level: 'info'      

    - name: Cache files 
      uses: actions/cache@v2
      env:
        cache-name: cache-files
      with:
        path: | 
          ./docs
          ./config
          ./pdfs
        key: $build-${{ env.cache-name }}-${{ github.event.head_commit.message }}
    - name: List the rendered files
      run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
    - name: MV the rendered files
      run: 'mv --backup=numbered -t ./docs/images ${{ steps.render.outputs.rendered-files }}'
      
  render_umlet:
    runs-on: ubuntu-latest
    name: Render umlet files
    needs: [render_drawio]
    steps:
    - name: Cache files 
      uses: actions/cache@v2
      env:
        cache-name: cache-files
      with:
        path: | 
          ./docs
          ./config
          ./pdfs
        key: $build2-${{ env.cache-name }}-${{ github.event.head_commit.message }}
        restore-keys: |
          $build-${{ env.cache-name }}-${{ github.event.head_commit.message }}
    - name: list files
      run: 'ls -laR'
    - name: update
      run: sudo apt-get update
    - name: upgrade
      run: sudo apt-get upgrade
    - name: Install Umlet
      run: sudo apt-get install umlet
    - name: render files
      run: 'sh ./config/render_umlet.sh'
      

  converttopdf:
    name: Build PDF with Pandoc
    needs: render_umlet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache files 
        uses: actions/cache@v2
        env:
          cache-name: cache-files
        with:
          path: | 
            ./docs
            ./config
            ./pdfs
          key: $build3-${{ env.cache-name }}-${{ github.event.head_commit.message }}
          restore-keys: |
            $build2-${{ env.cache-name }}-${{ github.event.head_commit.message }}
      - name: list files
        run: 'ls -laR'
      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=files::$(printf '"%s" ' docs/*.md)"
      - name: install pandoc
        run: sudo apt-get update;sudo apt-get install texlive-latex-base texlive-latex-extra pandoc libjs-mathjax; npm install --global mermaid-filter
      - name: run pandoc
        run: cd docs; for i in *.md ; do echo "$i" && pandoc --mathjax -F mermaid-filter -s $i -o ../pdfs/$i.pdf || true; done 
      - name: list files2
        run: 'ls -laR'        
      - uses: EndBug/add-and-commit@v7
        with:
          # This "special" author name and email will show up as the GH Actions user/bot in the UI
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Automatically render files'
          add: "."
